version: '3.8'

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../..:/workspaces:cached
    command: sleep infinity
    network_mode: host
    depends_on:
      - db1
      - db2
      - db3

  db1:
    image: postgres:latest
    restart: unless-stopped
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data-1:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres

  db2:
    image: postgres:latest
    restart: unless-stopped
    ports:
      - "5433:5432"
    volumes:
      - ./postgres-data-2:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres

  db3:
    image: postgres:latest
    restart: unless-stopped
    ports:
      - "5434:5432"
    volumes:
      - ./postgres-data-3:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres

volumes:
  postgres-data:
  postgres-data-1:
  postgres-data-2:
  postgres-data-3:
